# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 88daf6fb873a78ec68a780aafd1845063593a9ad7d5c626fb02d263bc94c1d848cddc4f9c352a5a605295a00eedaecf58c342f2b46561bdd582426b87d4f3a4a

test:
  secret_key_base: 7d4c4888fe8ca82075622b4f3f3c080528cbac2fafebe0eb08feabeadf1f6e9e4dbcc43a0c0daef0b1678ab1df6b464ae86334736ec82fd6786cf2c4d52c84d3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
