# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 34366e765dc3894b6850fd4a11b2c66a39d072582d28f2eea814e9950c104b2fa82efa9c547199095313a0e2ee6601f2c8d6df2f1deeb3ad474c1e2c9f35dd4b

test:
  secret_key_base: 0e86d17f899f80305f66850b2af018ecbd621b73d2bf57f90664baf49ebf1cdd9e47fe049f976195de27c9b25e31e1eca88db19fc78e5f0d7156eb6401b1ae2c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
